In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("assignment_4_salorno/salorno.csv")

In [3]:
df.head()

,Unnamed: 0,Unnamed: 1,day,sum,min_temp,max_temp,avg_temp,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,01.01.1993,0,-9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,02.01.1993,0,-9.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,03.01.1993,0,-4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,04.01.1993,0,-9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,05.01.1993,0,-5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df[['day', 'min_temp', 'max_temp']]
df["avg_temp"] = np.around((df["min_temp"] + df["max_temp"] )/2, decimals=2)
df.head()

          day  min_temp  max_temp  avg_temp
0  01.01.1993      -9.0       1.0      -4.0
1  02.01.1993      -9.0      -1.0      -5.0
2  03.01.1993      -4.0       1.0      -1.5
3  04.01.1993      -9.0       0.0      -4.5
4  05.01.1993      -5.0       2.0      -1.5

In [5]:
df.index = pd.to_datetime(df['day'], format='%d.%m.%Y')

In [6]:
df.head()

                   day  min_temp  max_temp  avg_temp
day
1993-01-01  01.01.1993      -9.0       1.0      -4.0
1993-01-02  02.01.1993      -9.0      -1.0      -5.0
1993-01-03  03.01.1993      -4.0       1.0      -1.5
1993-01-04  04.01.1993      -9.0       0.0      -4.5
1993-01-05  05.01.1993      -5.0       2.0      -1.5

ogni colonna:
    un mese gennaio - dicembre
ogni riga:
    temperature di ogni gg (30 valori)

In [60]:
years = [1993, 1997, 2001, 2005, 2009, 2013, 2017, 2021]
data_min_dict = {'year':[]}
data_max_dict = {'year':[]}
for y in years:
    counter = 31
    while counter != 0:
        data_min_dict['year'].append(y)
        data_max_dict['year'].append(y)
        counter -= 1

for x in range(1,13):
    data_min_dict[x] = []
    data_max_dict[x] = []

In [61]:
print(data_min_dict)

{'year': [1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1993, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 1997, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: []}

In [62]:
# aprile, giugno, settembre, novembre 30 giorni
# febbraio 28
count_min_apr = 0
count_max_apr = 0

count_min_jun = 0
count_max_jun = 0

count_min_sep = 0
count_max_sep = 0

count_min_nov = 0
count_max_nov = 0

count_min_feb = 0
count_max_feb = 0

for row in df.iterrows():
    date = row[0]
    if date.year not in years:
        continue
    tmin = row[1][1]
    tmax = row[1][2]
    
    data_min_dict[date.month].append(tmin)
    data_max_dict[date.month].append(tmax)

    if((date.month == 4 and len(data_min_dict[date.month])%30==count_min_apr)):
        data_min_dict[date.month].append('None')
        count_min_apr +=1
    
    if((date.month == 4 and len(data_max_dict[date.month])%30==count_max_apr)):
        data_max_dict[date.month].append('None')
        count_max_apr +=1
        
        

    if((date.month == 6 and len(data_min_dict[date.month])%30==count_min_jun)):
        data_min_dict[date.month].append('None')
        count_min_jun +=1
        
    if((date.month == 6 and len(data_max_dict[date.month])%30==count_max_jun)):
        data_max_dict[date.month].append('None')
        count_max_jun +=1
        
        
        
    if((date.month == 9 and len(data_min_dict[date.month])%30==count_min_sep)):
        data_min_dict[date.month].append('None')
        count_min_sep += 1
        
    if((date.month == 9 and len(data_max_dict[date.month])%30==count_max_sep)):
        data_max_dict[date.month].append('None')
        count_max_sep += 1
        
        
    if((date.month == 11 and len(data_min_dict[date.month])%30==count_min_nov)):
        data_min_dict[date.month].append('None')
        count_min_nov += 1
        
    if((date.month == 11 and len(data_max_dict[date.month])%30==count_max_nov)):
        data_max_dict[date.month].append('None')
        count_max_nov += 1
        
    if((date.month == 2 and len(data_min_dict[date.month])%28==count_min_feb)):
        data_min_dict[date.month].append('None')
        data_min_dict[date.month].append('None')
        data_min_dict[date.month].append('None')
        count_min_feb += 3

        
    if((date.month == 2 and len(data_max_dict[date.month])%28==count_max_feb)):
        data_max_dict[date.month].append('None')
        data_max_dict[date.month].append('None')
        data_max_dict[date.month].append('None')
        count_max_feb += 3

    
#print(data_min_dict)

In [36]:
print(data_min_dict[2])

[-3.0, -4.0, -2.0, -3.0, -4.0, -2.0, -1.0, -4.0, -5.0, -5.0, -3.0, -5.0, -4.0, -4.0, -6.0, -1.0, -4.0, -6.0, -4.0, -1.0, -2.0, -2.0, -3.0, -3.0, -5.0, -5.0, -5.0, -2.0, 'None', 'None', 'None', -4.0, -7.0, -6.0, -6.0, 0.0, -3.0, -4.0, -3.0, -4.0, -2.0, -3.0, 1.0, 3.0, 1.0, 0.0, -1.0, -3.0, -5.0, -1.0, -1.0, -3.0, -2.0, -2.0, 3.0, 4.0, 'None', 'None', 'None', 5.0, 5.0, 0.0, -2.0, -6.0, -6.0, -6.0, -2.0, -1.0, 4.0, 3.0, 4.0, 3.0, 2.0, -1.0, 0.0, 0.0, -2.0, -1.0, -3.0, 1.0, 0.0, 0.0, -2.0, 8.0, 'None', 'None', 'None', 0.0, 0.0, -3.0, -2.0, -5.0, -2.0, 0.4, -2.2, -3.3, -2.4, -2.4, -6.0, -6.8, -4.4, -2.6, -2.4, -2.8, -1.1, 2.2, 3.3, 0.4, 2.0, 0.4, -2.7, -3.2, 'None', 'None', 'None', -0.8, 0.6, -0.2, -1.1, -1.5, -2.3, 0.4, -3.4, -4.8, 0.4, 0.7, 1.3, 2.4, 3.7, 2.5, 2.5, 3.9, 1.4, 0.6, 3.4, -0.3, 0.6, -1.4, 1.1, -1.4, 'None', 'None', 'None', -3.9, -1.4, -4.8, -0.7, -1.4, -2.0, -1.4, -3.0, -1.9, -0.6, -0.1, 0.7, -1.4, 2.2, 1.7, 0.0, -2.2, 0.8, -0.3, -0.8, -0.8, -3.4, -3.0, -1.8, 0.5, 'None', 'None', 'None', -1.5, -2.1, -1.9, -0.6, 0.4, -1.2, -1.7, 0.4, -1.4, -2.9, -0.1, -0.6, 0.7, 2.6, 3.4, 2.6, 3.4, 4.0, 4.4, 3.2, 3.4, 4.7, 4.0, 1.2, 3.1, 'None', 'None', 'None', 2.9, 2.7, 1.8, 2.7, 2.6, 3.4, 0.9, 0.3, 1.5, -0.8, 2.6, 1.4, 6.2, 7.8, 2.7, -0.3, 1.2, 7.0, 1.2, 0.0, 2.3, 3.4, 2.6, 2.6, 4.2, 'None', 'None', 'None', 3.0, 2.7, 2.8, 0.0, -0.4, -2.3, -3.9, -3.5, -4.4, -0.7, -2.2, 2.6, 4.1, 4.0, 3.7, 3.9, 5.9, 5.9, 5.9, 5.8, 3.3]

In [235]:
# filling with nan all the missing values
for m in range(2, 13):
    len_d = len(data_min_dict[m])
    while len_d != 248:
        data_min_dict[m].append('None')
        len_d = len(data_min_dict[m])

for m in range(2, 13):
    len_d = len(data_max_dict[m])
    while len_d != 248:
        data_max_dict[m].append('None')
        len_d = len(data_max_dict[m])

In [63]:
df_min = pd.DataFrame(data_min_dict)
df_max = pd.DataFrame(data_max_dict)
df_min.rename(columns={1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sept', 10:'Oct', 11:'Nov', 12:'Dec'}, inplace=True)
df_max.rename(columns={1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sept', 10:'Oct', 11:'Nov', 12:'Dec'}, inplace=True)

In [64]:
df_min.head()

   year  Jan  Feb  Mar  Apr   May   Jun   Jul   Aug  Sept   Oct  Nov  Dec
0  1993 -9.0 -3.0  1.0 -1.0   6.0  13.0  15.0  13.0   9.0  11.0  4.0 -3.0
1  1993 -9.0 -4.0  1.0  6.0   7.0  14.0  16.0  17.0   9.0   9.0  8.0 -2.0
2  1993 -4.0 -2.0  1.0  6.0   7.0  13.0  17.0  16.0  11.0   9.0  7.0 -1.0
3  1993 -9.0 -3.0  0.0  4.0  10.0  13.0  14.0  17.0   8.0   6.0  6.0 -2.0
4  1993 -5.0 -4.0 -1.0  6.0   9.0  10.0  16.0  20.0   6.0   4.0  9.0 -2.0

In [65]:
df_max.head(40)

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec
0,1993,1.0,7.0,5.0,17.0,18.0,29.0,29.0,32.0,28.0,16.0,10.0,4.0
1,1993,-1.0,6.0,8.0,19.0,22.0,32.0,29.0,32.0,25.0,12.0,12.0,4.0
2,1993,1.0,7.0,9.0,15.0,23.0,21.0,30.0,35.0,22.0,18.0,15.0,7.0
3,1993,0.0,8.0,10.0,12.0,26.0,27.0,32.0,34.0,17.0,19.0,14.0,3.0
4,1993,2.0,6.0,7.0,20.0,26.0,31.0,31.0,33.0,26.0,17.0,12.0,7.0
5,1993,4.0,7.0,14.0,21.0,22.0,31.0,30.0,32.0,22.0,17.0,15.0,7.0
6,1993,5.0,11.0,13.0,30.0,22.0,32.0,31.0,31.0,23.0,17.0,16.0,2.0
7,1993,8.0,5.0,12.0,23.0,24.0,32.0,27.0,31.0,17.0,12.0,14.0,3.0
8,1993,5.0,10.0,12.0,19.0,25.0,31.0,28.0,31.0,19.0,17.0,12.0,6.0
9,1993,0.0,6.0,12.0,15.0,27.0,30.0,25.0,28.0,26.0,13.0,13.0,2.0
10,1993,3.0,5.0,15.0,14.0,23.0,27.0,23.0,31.0,24.0,14.0,13.0,6.0
11,1993,5.0,6.0,14.0,13.0,22.0,26.0,25.0,29.0,26.0,19.0,10.0,6.0
12,1993,5.0,7.0,15.0,11.0,21.0,21.0,27.0,33.0,19.0,21.0,11.0,4.0
13,1993,8.0,7.0,15.0,26.0,24.0,28.0,25.0,33.0,23.0,19.0,9.0,1.0
14,1993,8.0,7.0,17.0,18.0,28.0,28.0,26.0,33.0,23.0,17.0,13.0,4.0
15,1993,7.0,6.0,20.0,23.0,25.0,30.0,31.0,35.0,24.0,16.0,11.0,7.0
16,1993,1.0,4.0,27.0,21.0,26.0,29.0,30.0,37.0,24.0,12.0,5.0,7.0
17,1993,1.0,11.0,26.0,22.0,26.0,27.0,30.0,33.0,27.0,14.0,5.0,3.0
18,1993,3.0,8.0,25.0,21.0,28.0,29.0,26.0,31.0,27.0,14.0,4.0,4.0
19,1993,5.0,11.0,23.0,24.0,34.0,30.0,24.0,36.0,28.0,17.0,2.0,5.0
20,1993,4.0,7.0,20.0,22.0,23.0,28.0,28.0,32.0,29.0,15.0,1.0,7.0
21,1993,5.0,4.0,17.0,24.0,25.0,26.0,30.0,32.0,27.0,8.0,3.0,10.0
22,1993,2.0,2.0,16.0,24.0,27.0,24.0,30.0,32.0,28.0,13.0,2.0,1.0
23,1993,3.0,5.0,13.0,24.0,28.0,31.0,28.0,29.0,18.0,12.0,6.0,4.0
24,1993,12.0,8.0,11.0,19.0,30.0,26.0,27.0,30.0,17.0,12.0,5.0,4.0
25,1993,7.0,7.0,18.0,24.0,30.0,31.0,31.0,27.0,16.0,10.0,7.0,6.0
26,1993,9.0,7.0,10.0,27.0,28.0,28.0,26.0,20.0,18.0,10.0,5.0,6.0
27,1993,7.0,5.0,10.0,19.0,26.0,30.0,31.0,27.0,14.0,7.0,2.0,-1.0
28,1993,7.0,None,13.0,23.0,27.0,21.0,32.0,28.0,20.0,10.0,3.0,-2.0
29,1993,8.0,None,15.0,17.0,27.0,28.0,32.0,23.0,19.0,6.0,4.0,-1.0
30,1993,5.0,None,16.0,None,30.0,None,32.0,30.0,None,8.0,None,0.0
31,1997,1.0,6.0,13.0,24.0,25.0,16.0,24.0,26.0,31.0,23.0,9.0,13.0
32,1997,2.0,6.0,12.0,22.0,25.0,21.0,26.0,29.0,32.0,26.0,8.0,7.0
33,1997,3.0,1.0,17.0,26.0,28.0,25.0,26.0,30.0,31.0,24.0,9.0,8.0
34,1997,3.0,4.0,17.0,20.0,25.0,25.0,28.0,32.0,31.0,22.0,12.0,8.0
35,1997,2.0,4.0,18.0,18.0,19.0,21.0,22.0,32.0,31.0,21.0,10.0,2.0
36,1997,4.0,11.0,16.0,20.0,15.0,27.0,28.0,32.0,31.0,21.0,10.0,2.0
37,1997,4.0,3.0,15.0,19.0,18.0,29.0,24.0,27.0,26.0,21.0,16.0,0.0
38,1997,2.0,5.0,16.0,15.0,16.0,27.0,31.0,30.0,30.0,24.0,14.0,3.0
39,1997,2.0,6.0,16.0,18.0,19.0,30.0,29.0,35.0,32.0,23.0,11.0,3.0

In [70]:
df_max.tail(50)

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec
198,2017,5.4,10.4,16.1,23.3,26.2,32.2,31.9,28.2,18.8,19.3,10.7,7.8
199,2017,5.5,11.5,21.1,22.8,25.8,27.4,27.0,28.8,20.2,20.6,12.6,3.4
200,2017,5.3,12.2,16.9,20.1,25.5,31.3,28.3,30.2,18.8,19.5,11.7,6.5
201,2017,4.1,13.8,20.2,21.7,27.2,32.2,28.6,28.2,18.0,20.8,10.6,6.0
202,2017,5.0,11.3,20.6,16.3,27.7,32.4,29.2,30.7,16.4,19.2,11.0,6.5
203,2017,5.7,12.7,19.5,13.6,26.1,30.8,30.9,31.7,18.0,20.3,10.6,3.0
204,2017,5.1,11.7,17.5,12.3,23.6,31.5,30.8,26.4,17.0,18.5,13.4,0.9
205,2017,4.5,12.0,19.4,14.2,21.7,33.3,30.3,26.0,20.2,18.6,8.7,2.8
206,2017,5.3,10.8,16.7,18.8,26.4,33.1,28.8,26.3,19.7,18.0,7.2,2.2
207,2017,5.7,9.7,16.2,20.6,27.4,32.4,30.0,25.7,21.7,14.6,8.2,1.0
208,2017,5.3,10.4,16.6,21.3,28.7,32.7,31.1,27.6,20.6,18.1,9.9,10.1
209,2017,6.4,11.9,19.3,16.3,28.7,33.7,23.3,30.0,21.4,21.2,8.5,9.4
210,2017,6.2,13.0,22.6,18.4,28.4,27.1,25.0,30.5,20.4,16.2,9.2,3.3
211,2017,5.8,11.6,17.8,15.1,27.3,30.7,26.1,30.7,21.7,16.2,10.7,3.1
212,2017,4.5,13.3,18.0,15.5,29.2,26.6,27.4,28.8,21.7,20.7,8.4,2.1
213,2017,5.0,9.4,20.9,13.8,30.5,25.8,30.0,27.6,21.5,15.3,3.2,7.1
214,2017,6.5,None,23.5,18.6,30.7,25.1,31.0,29.4,20.6,19.2,3.5,4.7
215,2017,5.9,None,24.0,19.5,31.2,23.0,30.4,29.7,19.7,17.6,8.7,3.1
216,2017,3.9,None,23.6,None,30.6,None,31.6,29.7,None,12.6,None,2.2
217,2021,0.4,6.8,13.9,25.6,20.3,25.5,28.1,21.1,26.8,21.8,10.9,5.7
218,2021,2.3,7.3,15.4,25.1,19.9,25.9,30.2,24.1,26.6,21.6,13.8,7.6
219,2021,3.3,4.2,12.9,18.9,19.8,27.9,30.8,21.0,26.7,18.2,8.4,8.4
220,2021,4.3,9.6,13.6,17.7,20.6,29.1,25.5,21.5,27.3,22.0,9.2,4.0
221,2021,3.5,7.8,14.5,15.9,20.7,29.0,28.4,27.3,27.8,19.8,11.5,7.0
222,2021,2.9,7.1,11.5,10.7,19.0,26.6,31.7,27.8,27.6,16.1,10.7,7.7
223,2021,0.8,5.9,12.4,9.2,21.8,23.1,33.5,27.8,27.5,19.5,11.5,4.2
224,2021,1.7,10.4,13.2,15.7,21.7,26.9,27.7,28.7,27.6,20.3,8.5,1.7
225,2021,-0.6,8.2,13.4,15.4,24.5,27.6,29.5,29.2,27.8,18.3,10.5,6.6
226,2021,-0.3,7.0,13.8,16.1,26.6,27.3,30.5,29.7,27.7,16.5,13.2,1.7
227,2021,-1.5,8.8,10.6,11.5,19.8,27.7,29.1,31.2,28.7,18.1,14.1,8.8
228,2021,-1.4,2.9,14.4,12.2,17.6,30.9,31.0,31.9,28.4,13.6,13.1,9.5
229,2021,4.2,4.8,15.5,12.7,21.8,33.0,26.5,30.3,29.7,17.4,9.8,8.0
230,2021,7.3,2.8,12.2,13.5,20.6,30.7,22.2,32.7,29.6,15.5,10.0,6.8
231,2021,4.1,3.6,13.4,10.8,18.7,29.4,22.8,32.9,24.1,13.7,12.1,6.5
232,2021,2.7,8.0,12.5,14.8,21.0,30.2,23.5,28.0,20.4,17.5,10.6,5.6
233,2021,-0.5,10.0,12.5,16.9,22.2,31.9,28.7,26.4,26.7,15.5,12.4,6.8
234,2021,0.7,10.1,10.3,16.2,23.0,31.4,30.9,27.4,25.7,16.8,13.6,6.5
235,2021,1.5,11.8,10.0,16.7,20.1,32.6,32.2,27.7,20.0,14.2,11.4,8.0
236,2021,2.1,13.5,8.9,19.0,22.5,32.4,30.9,28.6,22.8,17.5,11.5,7.7
237,2021,1.2,13.0,12.5,19.5,22.1,32.6,31.3,29.4,23.0,16.3,11.5,2.4
238,2021,3.2,13.2,13.6,21.0,19.7,32.1,29.9,26.8,19.5,18.0,10.5,1.8
239,2021,8.2,14.7,15.8,22.2,20.0,33.6,29.7,26.1,21.7,15.4,11.8,1.9
240,2021,6.1,16.4,18.5,22.7,14.0,31.0,30.2,27.6,23.8,13.2,8.8,2.9
241,2021,2.9,16.2,19.8,24.1,19.9,30.1,28.5,26.0,23.8,12.1,4.7,5.4
242,2021,6.6,15.9,18.7,16.4,22.7,30.7,23.4,26.9,20.0,13.0,6.7,5.8
243,2021,2.3,18.9,17.1,18.4,23.0,31.7,24.3,25.3,24.4,13.2,8.0,6.0
244,2021,2.6,14.7,19.2,21.6,24.8,33.6,28.7,23.9,24.8,12.6,5.5,6.3
245,2021,2.8,None,21.9,17.3,22.0,32.2,29.8,22.5,22.2,15.1,7.8,10.7
246,2021,6.2,None,25.3,20.6,24.5,29.8,30.2,20.9,22.7,13.1,3.5,9.9
247,2021,6.8,None,25.2,None,23.2,None,30.1,23.8,None,14.5,None,11.5

In [67]:
df_min.to_csv('data/ass_4_ridgeline_min.csv')
df_max.to_csv('data/ass_4_ridgeline_max.csv')